# Generated by Django 5.2.4 on 2025-08-04 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powerdata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='powerdata',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
