# Generated by Django 5.2.4 on 2025-07-31 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_powerdata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PowerData',
        ),
    ]
