# Generated by Django 5.2.4 on 2025-08-06 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_country_customuser_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='position',
            field=models.CharField(choices=[('global_admin', 'Global Admin'), ('country_manager', 'Country Manager'), ('station_manager', 'Station Manager')], default='station_manager', max_length=20),
        ),
    ]
