# Generated by Django 5.2.4 on 2025-08-06 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_customuser_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='position',
            field=models.CharField(choices=[('global_admin', 'Global Admin'), ('country_manager', 'Country Manager'), ('station_manager', 'Station Manager')], default='station manager', max_length=20),
        ),
    ]
